const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('#main-nav');if(menuButton&&nav){menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');document.body.classList.toggle('menu-open',open);menuButton.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('menu-open');menuButton.setAttribute('aria-expanded','false')}))}document.querySelectorAll('#year').forEach(year=>year.textContent=new Date().getFullYear());

const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const revealTargets=document.querySelectorAll('.section-heading,.welcome-grid,.identity-card,.history-feature,.schedule-grid article,.ministry-list article,.gallery-grid figure,.location-card,.quick-paths a,.verse-inner,.belief-grid article,.ministry-detail,.timeline-tree article,.collection-card,.photo-collection');
revealTargets.forEach((element,index)=>{element.classList.add('reveal');element.style.transitionDelay=`${Math.min(index%5,4)*70}ms`});
if(reduceMotion){revealTargets.forEach(element=>element.classList.add('visible'))}else{const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.12});revealTargets.forEach(element=>observer.observe(element));const heroImage=document.querySelector('.hero>img');if(heroImage)window.addEventListener('scroll',()=>{if(window.scrollY<window.innerHeight)heroImage.style.transform=`scale(1.04) translateY(${window.scrollY*.09}px)`},{passive:true})}
const siteHeader=document.querySelector('.site-header');const updateHeader=()=>siteHeader.classList.toggle('scrolled',window.scrollY>48);updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});

// Orientación y microinteracciones
const progress=document.createElement('div');progress.className='reading-progress';progress.setAttribute('aria-hidden','true');document.body.prepend(progress);
const topButton=document.createElement('button');topButton.className='back-to-top';topButton.type='button';topButton.setAttribute('aria-label','Volver al inicio');topButton.innerHTML='↑';document.body.append(topButton);topButton.addEventListener('click',()=>window.scrollTo({top:0,behavior:reduceMotion?'auto':'smooth'}));
const updateScrollUI=()=>{const available=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${available>0?scrollY/available:0})`;topButton.classList.toggle('visible',scrollY>650)};updateScrollUI();window.addEventListener('scroll',updateScrollUI,{passive:true});
if(nav&&(location.pathname.endsWith('index.html')||location.pathname.endsWith('/'))){const sections=[...document.querySelectorAll('main section[id]')];const sectionLinks=[...nav.querySelectorAll('a[href^="#"]')];if(sections.length&&sectionLinks.length){const sectionObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)sectionLinks.forEach(link=>link.classList.toggle('section-active',link.getAttribute('href')===`#${entry.target.id}`))})},{rootMargin:'-35% 0px -55%'});sections.forEach(section=>sectionObserver.observe(section))}}
if(!reduceMotion&&matchMedia('(pointer:fine)').matches){document.querySelectorAll('.identity-card,.collection-card,.belief-grid article').forEach(card=>{card.addEventListener('pointermove',event=>{const box=card.getBoundingClientRect();card.style.setProperty('--mx',`${event.clientX-box.left}px`);card.style.setProperty('--my',`${event.clientY-box.top}px`)});card.addEventListener('pointerleave',()=>{card.style.removeProperty('--mx');card.style.removeProperty('--my')})})}
document.querySelectorAll('.masonry-gallery img,.photo-wall img').forEach(image=>{image.tabIndex=0;image.setAttribute('role','button');image.addEventListener('click',()=>openLightbox(image));image.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')openLightbox(image)})});
function openLightbox(image){const modal=document.createElement('div');modal.className='lightbox';modal.innerHTML=`<button aria-label="Cerrar imagen">×</button><img src="${image.currentSrc||image.src}" alt="${image.alt}"><p>${image.alt}</p>`;document.body.append(modal);requestAnimationFrame(()=>modal.classList.add('open'));const close=()=>{modal.classList.remove('open');setTimeout(()=>modal.remove(),220)};modal.addEventListener('click',event=>{if(event.target===modal||event.target.tagName==='BUTTON')close()});document.addEventListener('keydown',function esc(event){if(event.key==='Escape'){close();document.removeEventListener('keydown',esc)}})}
